# GitHub Actions workflow cho kiểm tra và deploy từ nhánh dev
name: CI/CD Pipeline

# Trigger pipeline khi có push vào nhánh dev
on:
  push:
    branches: [ dev ]

jobs:
  # Job kiểm tra code và deploy
  test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci || npm install
    
    - name: Run tests
      run: npm test
    
    # Deploy lên Render trực tiếp từ nhánh dev sau khi kiểm tra thành công
    - name: Deploy to Render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}